### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by icefo** [concordusapps/strudel#9]
First, I'm a Python beginner in search of a Vcard parser working with python3 and I'm having some troubles to understand how to use your app. I looked at the example and test files but they both seem to be working with a previous release.

Example: if I run the example file ( I figured ou the import part )

<pre><code>
from strudel.vobj import VCard

vcf = VCard()
vcf.full_name = "Ryan Leckey"
vcf.name.first = "Ryan"
vcf.name.last = "Leckey"
vcf.phone.append("916-800-2370", attributes="..", label="Bobs")
</code></pre>

Python throw me an error :

<pre><code>
Traceback (most recent call last):
  File "/..../main.py", line 7, in <module>
    vcf.phone.append("916-800-2370", attributes="..", label="Bobs")
  File "/..../lib/python3.4/site-packages/strudel/vobj.py", line 154, in phone
    return self._data['TEL'][0]
IndexError: list index out of range
</code></pre>

So do you have a link to some doc ? If no could show me how to import the "strudel/strudel/fixtures/multicard_2.1.vcf" file, delete / edit / access some records and then save it ?
PS : I understand that you have no obligation to do it but it would be nice :-)

**Comment by jcbsv** [comment]
+1 some documentation, or working examples would be greatly appreciated ;-)

**Comment by icefo** [comment]
The project seems to be dead. If you really need a vcard parser you'll have to write one yourself. You might want to look at http://pyparsing.wikispaces.com/ to write the parser.
Good luck !

**Comment by off-by-some** [comment]
I'll be forking and writing some docs/bugfixes/proper error handling possibly sometime this weekend or the next as @icefo is correct, this is a dead project.. The company has since dissolved and there are no active contributors to any of these repositories

**Comment by icefo** [comment]
Thank you ! That might come handy one day

**Comment by jcbsv** [comment]
I went with [card-me](https://pypi.python.org/pypi/python-card-me), which is a recent Python 3 fork of vobject.

**Comment by off-by-some** [comment]
@icefo @jcbsnd, After many hours of pain and suffering in the strudel code base, i decided it would be best to rewrite it [here](https://github.com/Pholey/vcfx) , Its not done quite _yet_, but it is useable.. most of the work has been done and adding support for fields is rather painless at this point (should be completed within the next week honestly)
